#!/usr/bin/env
#
# Copyright 2020, Institute for Systems Biology
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import argparse
import os
import sys
import json

from BQ.gen_collection_id_table import build_collections_id_table

parser =argparse.ArgumentParser()
parser.add_argument('--save_file', default='{}/BQ/lists/collection_ids_release.json'.format(os.environ['PWD']),
                    help="File in which to save results")
parser.add_argument('--collections', default='{}/lists/idc_mvp_wave_0.txt'.format(os.environ['PWD']),
                    help="File containing list of IDC collection IDs or 'all' for all collections")

args = parser.parse_args()
print("{}".format(args), file=sys.stdout)
collection_ids = build_collections_id_table(args)

with open(args.save_file, 'w') as f:
    #        print('# This table was generated by gen_collection_id_table.py')
    json.dump(collection_ids, f)
